---
- name: Create frontend directory
  file:
    path: "{{ deploy_path }}/frontend"
    state: directory
    mode: '0755'

- name: Ensure /app/frontend directory exists
  file:
    path: /app/frontend
    state: directory
    mode: '0755'

- name: Copy frontend files
  copy:
    src: "{{ playbook_dir }}/../frontend"
    dest: /app/frontend

