version: '3.9'

services:
  mental-health-backend:
    build:
      context: ./backend
    container_name: mental-health-backend
    ports:
      - "5001:5001"
    restart: always 

  mental-health-frontend:
    build:
      context: ./frontend
    container_name: mental-health-frontend
    ports:
      - "5003:5003"
    depends_on:
      - mental-health-backend
    restart: alway
