---
app_name: mental-health
backend_port: 5001
frontend_port: 5003
project_root: "/home/naman/Desktop/Tanvi_MLOps_Code"
deploy_path: "/opt/mental-health"
k8s_dir: "{{ project_root }}/kubernetes"  # Explicit kubernetes directory

backend_container_name: mental-health-backend
frontend_container_name: mental-health-frontend

# DO NOT hardcode username/password here
docker_registry: "{{ vault_docker_username }}"
backend_image: "{{ docker_registry }}/mental-health-backend:latest"
frontend_image: "{{ docker_registry }}/mental-health-frontend:latest"
