apiVersion: v1
kind: Service
metadata:
  name: mental-health-frontend-service
spec:
  selector:
    app: mental-health-frontend
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
    nodePort: 31545
  type: NodePort
