apiVersion: apps/v1
kind: Deployment
metadata:
  name: mental-health-frontend-deployment
  labels:
    app: mental-health-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mental-health-frontend
  template:
    metadata:
      labels:
        app: mental-health-frontend
    spec:
      containers:
      - name: frontend
        image: tanvikulkarni33/mental-health-frontend:latest
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
