- name: Create ELK namespace (if needed)
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: default
    state: present

- name: Apply Elasticsearch deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/elk/elasticsearch-deployment.yml"

- name: Apply Kibana deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/elk/kibana-deployment.yml"

- name: Apply Logstash config
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/elk/logstash-configmap.yml"

- name: Apply Logstash deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/elk/logstash-deployment.yml"

- name: Apply Filebeat daemonset
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/elk/filebeat-kubernetes.yaml"
