apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default  # Same namespace as your DaemonSet
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      stream: all 
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ['elasticsearch:9200']
      indices:
        - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"